package fastapi

import (
	"regexp"

	"github.com/Patchflow-security/patchflow-cli/internal/analysis"
	"github.com/Patchflow-security/patchflow-cli/internal/sast/frameworks"
)

// Rules returns the FastAPI framework rules.
func Rules() []frameworks.FrameworkRule {
	return []frameworks.FrameworkRule{
		{
			ID:             "PF-FASTAPI-SQLI-001",
			Framework:      "fastapi",
			Language:       "python",
			CWE:            "CWE-89",
			Title:          "FastAPI SQLi: execute with interpolated request data",
			Severity:       analysis.SeverityHigh,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityExperimental,
			FileTypes:      []string{".py"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`\.(execute|executemany)\s*\(\s*(f["']|["'][^"']*(\{|\+|%s)|.*request\.(query_params|path_params|headers|cookies))`),
			Sanitizers:     Sanitizers,
			Recommendation: "Use parameterized queries or bound parameters. Never interpolate request data into SQL strings.",
		},
		{
			ID:             "PF-FASTAPI-SSRF-001",
			Framework:      "fastapi",
			Language:       "python",
			CWE:            "CWE-918",
			Title:          "FastAPI SSRF: outbound HTTP call with request-controlled URL",
			Severity:       analysis.SeverityHigh,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityExperimental,
			FileTypes:      []string{".py"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`(requests|httpx)\.(get|post|request)\s*\(\s*(f["']|request\.(query_params|path_params|headers|cookies)|.*\[(["'])(url|target|host)["']\])`),
			Sanitizers:     Sanitizers,
			Recommendation: "Validate outbound URLs against an allowlist of permitted hosts before making HTTP requests.",
		},
		{
			ID:             "PF-FASTAPI-REDIRECT-001",
			Framework:      "fastapi",
			Language:       "python",
			CWE:            "CWE-601",
			Title:          "FastAPI open redirect: RedirectResponse with request input",
			Severity:       analysis.SeverityMedium,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityExperimental,
			FileTypes:      []string{".py"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`RedirectResponse\s*\(\s*(url\s*=\s*)?(request\.(query_params|path_params|headers|cookies)|.*\[(["'])(next|redirect|url)["']\])`),
			Sanitizers:     Sanitizers,
			Recommendation: "Validate redirect targets against an allowlist of hosts or constrain them to known relative paths.",
		},
		{
			ID:             "PF-FASTAPI-CMDI-001",
			Framework:      "fastapi",
			Language:       "python",
			CWE:            "CWE-78",
			Title:          "FastAPI command injection: subprocess with request data",
			Severity:       analysis.SeverityCritical,
			Confidence:     analysis.ConfidenceHigh,
			Maturity:       frameworks.MaturityExperimental,
			FileTypes:      []string{".py"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`subprocess\.(run|Popen|call|check_output|check_call)\s*\([^)]*request\.(query_params|path_params|headers|cookies)`),
			Recommendation: "Do not pass request-controlled data to subprocess. Use fixed argument lists or strict allowlists.",
		},
		{
			ID:             "PF-FASTAPI-PATH-001",
			Framework:      "fastapi",
			Language:       "python",
			CWE:            "CWE-22",
			Title:          "FastAPI path traversal: FileResponse/open with request input",
			Severity:       analysis.SeverityHigh,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityExperimental,
			FileTypes:      []string{".py"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`(FileResponse|open)\s*\(\s*(request\.(query_params|path_params)|.*\[(["'])(file|path|filename)["']\])`),
			Sanitizers:     Sanitizers,
			Recommendation: "Resolve paths against a fixed base directory and validate that the final path stays within it.",
		},
		{
			ID:             "PF-FASTAPI-XSS-001",
			Framework:      "fastapi",
			Language:       "python",
			CWE:            "CWE-79",
			Title:          "FastAPI template XSS: Jinja safe filter",
			Severity:       analysis.SeverityHigh,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityExperimental,
			TemplateTypes:  []string{".jinja", ".jinja2", ".html"},
			MatchMode:      frameworks.MatchTemplate,
			Pattern:        regexp.MustCompile(`\|\s*safe\b`),
			Sanitizers:     Sanitizers,
			Recommendation: "Avoid Jinja's safe filter on user-controlled data. Let auto-escaping run or escape explicitly.",
		},
		{
			ID:             "PF-FASTAPI-SQLI-002",
			Framework:      "fastapi",
			Language:       "python",
			CWE:            "CWE-89",
			Title:          "FastAPI SQLi (taint): request data reaches execute/text()",
			Severity:       analysis.SeverityHigh,
			Confidence:     analysis.ConfidenceHigh,
			Maturity:       frameworks.MaturityExperimental,
			FileTypes:      []string{".py"},
			MatchMode:      frameworks.MatchTaint,
			Sources:        Sources,
			Sinks:          []frameworks.SinkPattern{
				{FuncName: "execute", ArgIndex: 0},
				{FuncName: "executemany", ArgIndex: 0},
				{FuncName: "text", ArgIndex: 0},
				{FuncName: "session.execute", ArgIndex: 0},
			},
			Sanitizers:     Sanitizers,
			Recommendation: "Use bound parameters or ORM query APIs. Tainted request data reached a SQL execution sink.",
		},
		{
			ID:             "PF-FASTAPI-REDIRECT-002",
			Framework:      "fastapi",
			Language:       "python",
			CWE:            "CWE-601",
			Title:          "FastAPI open redirect (taint): request data reaches RedirectResponse",
			Severity:       analysis.SeverityMedium,
			Confidence:     analysis.ConfidenceHigh,
			Maturity:       frameworks.MaturityExperimental,
			FileTypes:      []string{".py"},
			MatchMode:      frameworks.MatchTaint,
			Sources:        Sources,
			Sinks:          []frameworks.SinkPattern{{FuncName: "RedirectResponse", ArgIndex: 0}},
			Sanitizers:     Sanitizers,
			Recommendation: "Validate redirect targets before passing them into RedirectResponse.",
		},
		{
			ID:             "PF-FASTAPI-AUTH-001",
			Framework:      "fastapi",
			Language:       "python",
			CWE:            "CWE-862",
			Title:          "FastAPI missing auth: sensitive endpoint without Depends(auth)",
			Severity:       analysis.SeverityMedium,
			Confidence:     analysis.ConfidenceLow,
			Maturity:       frameworks.MaturityExperimental,
			FileTypes:      []string{".py"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`@(app|router)\.(get|post|put|delete|patch)\s*\(\s*["'][^"']*(?i:admin|delete|user|account|config|setting|secret|password|token|billing|payment)["']`),
			Sanitizers:     Sanitizers,
			SafePatterns: []frameworks.SafePattern{
				{Regex: regexp.MustCompile(`Depends\s*\(`), Reason: "Endpoint uses Depends() — may include auth dependency."},
				{Regex: regexp.MustCompile(`(current_user|get_current_user|require_auth|require_admin|verify_token)`), Reason: "Auth dependency or check present."},
			},
			Recommendation: "Sensitive endpoints should require authentication via Depends(get_current_user) or equivalent. FastAPI supports global, router, and per-endpoint dependencies.",
		},
	}
}
