package taintpatterns

import "github.com/patchflow/patchflow-cli/internal/analysis"

// builtInRules returns the built-in taint pattern rules for Python and JS/TS.
// These rules define source-sink pairs for common injection vulnerabilities.
func builtInRules() []Rule {
	return []Rule{
		// === Python taint rules ===
		{
			ID:          "TP-PY001",
			Title:       "SQL injection (tainted data in cursor.execute)",
			Description: "User input flows into a SQL query without parameterization. Use parameterized queries instead of string concatenation.",
			Severity:    analysis.SeverityHigh,
			Confidence:  analysis.ConfidenceMedium,
			Language:    "python",
			CWEID:       "CWE-89",
			Sources: []SourcePattern{
				{FuncName: "request.GET", IsSubscript: true},
				{FuncName: "request.POST", IsSubscript: true},
				{FuncName: "request.args", IsSubscript: true},
				{FuncName: "request.form", IsSubscript: true},
				{FuncName: "request.values", IsSubscript: true},
				{FuncName: "request.cookies", IsSubscript: true},
				{FuncName: "request.headers", IsSubscript: true},
				{FuncName: "request.json", IsSubscript: true},
				{FuncName: "input"},
				{FuncName: "sys.argv", IsSubscript: true},
				{FuncName: "os.environ", IsSubscript: true},
			},
			Sinks: []SinkPattern{
				{FuncName: "execute", ArgIndex: 0},
				{FuncName: "executemany", ArgIndex: 0},
				{FuncName: "executescript", ArgIndex: 0},
			},
		},
		{
			ID:          "TP-PY002",
			Title:       "Command injection (tainted data in os.system/subprocess)",
			Description: "User input flows into a command execution function. Use subprocess with shell=False and argument lists.",
			Severity:    analysis.SeverityHigh,
			Confidence:  analysis.ConfidenceMedium,
			Language:    "python",
			CWEID:       "CWE-78",
			Sources: []SourcePattern{
				{FuncName: "request.GET", IsSubscript: true},
				{FuncName: "request.POST", IsSubscript: true},
				{FuncName: "request.args", IsSubscript: true},
				{FuncName: "request.form", IsSubscript: true},
				{FuncName: "input"},
				{FuncName: "sys.argv", IsSubscript: true},
			},
			Sinks: []SinkPattern{
				{FuncName: "os.system", ArgIndex: 0},
				{FuncName: "subprocess.call", ArgIndex: 0},
				{FuncName: "subprocess.run", ArgIndex: 0},
				{FuncName: "subprocess.Popen", ArgIndex: 0},
				{FuncName: "subprocess.check_output", ArgIndex: 0},
				{FuncName: "os.popen", ArgIndex: 0},
			},
		},
		{
			ID:          "TP-PY003",
			Title:       "Path traversal (tainted data in file operations)",
			Description: "User input flows into a file path. Validate and sanitize file paths, use os.path.abspath to prevent traversal.",
			Severity:    analysis.SeverityHigh,
			Confidence:  analysis.ConfidenceMedium,
			Language:    "python",
			CWEID:       "CWE-22",
			Sources: []SourcePattern{
				{FuncName: "request.GET", IsSubscript: true},
				{FuncName: "request.POST", IsSubscript: true},
				{FuncName: "request.args", IsSubscript: true},
				{FuncName: "request.form", IsSubscript: true},
				{FuncName: "input"},
			},
			Sinks: []SinkPattern{
				{FuncName: "open", ArgIndex: 0},
				{FuncName: "os.open", ArgIndex: 0},
				{FuncName: "os.remove", ArgIndex: 0},
				{FuncName: "os.unlink", ArgIndex: 0},
				{FuncName: "shutil.copy", ArgIndex: -1},
				{FuncName: "shutil.move", ArgIndex: -1},
			},
		},
		{
			ID:          "TP-PY004",
			Title:       "SSRF (tainted data in HTTP requests)",
			Description: "User input flows into an HTTP request URL. Validate URLs and restrict allowed hosts.",
			Severity:    analysis.SeverityMedium,
			Confidence:  analysis.ConfidenceMedium,
			Language:    "python",
			CWEID:       "CWE-918",
			Sources: []SourcePattern{
				{FuncName: "request.GET", IsSubscript: true},
				{FuncName: "request.POST", IsSubscript: true},
				{FuncName: "request.args", IsSubscript: true},
				{FuncName: "input"},
			},
			Sinks: []SinkPattern{
				{FuncName: "requests.get", ArgIndex: 0},
				{FuncName: "requests.post", ArgIndex: 0},
				{FuncName: "requests.put", ArgIndex: 0},
				{FuncName: "requests.delete", ArgIndex: 0},
				{FuncName: "urllib.request.urlopen", ArgIndex: 0},
				{FuncName: "urlopen", ArgIndex: 0},
			},
		},
		{
			ID:          "TP-PY005",
			Title:       "Code injection (tainted data in eval/exec)",
			Description: "User input flows into eval() or exec(). Avoid dynamic code execution with untrusted input.",
			Severity:    analysis.SeverityHigh,
			Confidence:  analysis.ConfidenceHigh,
			Language:    "python",
			CWEID:       "CWE-94",
			Sources: []SourcePattern{
				{FuncName: "request.GET", IsSubscript: true},
				{FuncName: "request.POST", IsSubscript: true},
				{FuncName: "request.args", IsSubscript: true},
				{FuncName: "input"},
				{FuncName: "sys.argv", IsSubscript: true},
			},
			Sinks: []SinkPattern{
				{FuncName: "eval", ArgIndex: 0},
				{FuncName: "exec", ArgIndex: 0},
				{FuncName: "compile", ArgIndex: 0},
			},
		},
		{
			ID:          "TP-PY006",
			Title:       "XSS (tainted data in template rendering)",
			Description: "User input flows into template rendering without escaping. Use auto-escaping templates.",
			Severity:    analysis.SeverityMedium,
			Confidence:  analysis.ConfidenceMedium,
			Language:    "python",
			CWEID:       "CWE-79",
			Sources: []SourcePattern{
				{FuncName: "request.GET", IsSubscript: true},
				{FuncName: "request.POST", IsSubscript: true},
				{FuncName: "request.args", IsSubscript: true},
				{FuncName: "input"},
			},
			Sinks: []SinkPattern{
				{FuncName: "render", ArgIndex: -1},
				{FuncName: "make_response", ArgIndex: -1},
				{FuncName: "HttpResponse", ArgIndex: -1},
			},
		},

		// === JavaScript/TypeScript taint rules ===
		{
			ID:          "TP-JS001",
			Title:       "SQL injection (tainted data in query execution)",
			Description: "User input flows into a SQL query without parameterization. Use parameterized queries.",
			Severity:    analysis.SeverityHigh,
			Confidence:  analysis.ConfidenceMedium,
			Language:    "javascript",
			CWEID:       "CWE-89",
			Sources: []SourcePattern{
				{FuncName: "req.query", IsSubscript: true},
				{FuncName: "req.params", IsSubscript: true},
				{FuncName: "req.body", IsSubscript: true},
				{FuncName: "req.headers", IsSubscript: true},
				{FuncName: "req.cookies", IsSubscript: true},
				{FuncName: "request.query", IsSubscript: true},
				{FuncName: "request.body", IsSubscript: true},
				{FuncName: "event.queryStringParameters", IsSubscript: true},
				{FuncName: "event.body", IsSubscript: true},
			},
			Sinks: []SinkPattern{
				{FuncName: "query", ArgIndex: 0},
				{FuncName: "execute", ArgIndex: 0},
				{FuncName: "raw", ArgIndex: 0},
				{FuncName: "db.query", ArgIndex: 0},
			},
		},
		{
			ID:          "TP-JS002",
			Title:       "Command injection (tainted data in child_process)",
			Description: "User input flows into a command execution function. Use execFile with argument arrays.",
			Severity:    analysis.SeverityHigh,
			Confidence:  analysis.ConfidenceMedium,
			Language:    "javascript",
			CWEID:       "CWE-78",
			Sources: []SourcePattern{
				{FuncName: "req.query", IsSubscript: true},
				{FuncName: "req.params", IsSubscript: true},
				{FuncName: "req.body", IsSubscript: true},
				{FuncName: "process.argv", IsSubscript: true},
			},
			Sinks: []SinkPattern{
				{FuncName: "exec", ArgIndex: 0},
				{FuncName: "execSync", ArgIndex: 0},
				{FuncName: "spawn", ArgIndex: 0},
				{FuncName: "spawnSync", ArgIndex: 0},
			},
		},
		{
			ID:          "TP-JS003",
			Title:       "XSS (tainted data in response send)",
			Description: "User input flows into HTTP response without escaping. Use proper output encoding.",
			Severity:    analysis.SeverityMedium,
			Confidence:  analysis.ConfidenceMedium,
			Language:    "javascript",
			CWEID:       "CWE-79",
			Sources: []SourcePattern{
				{FuncName: "req.query", IsSubscript: true},
				{FuncName: "req.params", IsSubscript: true},
				{FuncName: "req.body", IsSubscript: true},
			},
			Sinks: []SinkPattern{
				{FuncName: "send", ArgIndex: 0},
				{FuncName: "write", ArgIndex: 0},
				{FuncName: "innerHTML", ArgIndex: -1},
				{FuncName: "insertAdjacentHTML", ArgIndex: 1},
				{FuncName: "document.write", ArgIndex: 0},
			},
		},
		{
			ID:          "TP-JS004",
			Title:       "Path traversal (tainted data in file operations)",
			Description: "User input flows into a file path. Use path.resolve() and validate against a base directory.",
			Severity:    analysis.SeverityHigh,
			Confidence:  analysis.ConfidenceMedium,
			Language:    "javascript",
			CWEID:       "CWE-22",
			Sources: []SourcePattern{
				{FuncName: "req.query", IsSubscript: true},
				{FuncName: "req.params", IsSubscript: true},
				{FuncName: "req.body", IsSubscript: true},
			},
			Sinks: []SinkPattern{
				{FuncName: "readFile", ArgIndex: 0},
				{FuncName: "readFileSync", ArgIndex: 0},
				{FuncName: "writeFile", ArgIndex: 0},
				{FuncName: "writeFileSync", ArgIndex: 0},
				{FuncName: "createReadStream", ArgIndex: 0},
				{FuncName: "createWriteStream", ArgIndex: 0},
				{FuncName: "unlink", ArgIndex: 0},
				{FuncName: "unlinkSync", ArgIndex: 0},
			},
		},
		{
			ID:          "TP-JS005",
			Title:       "SSRF (tainted data in HTTP requests)",
			Description: "User input flows into an HTTP request URL. Validate and restrict allowed hosts.",
			Severity:    analysis.SeverityMedium,
			Confidence:  analysis.ConfidenceMedium,
			Language:    "javascript",
			Sources: []SourcePattern{
				{FuncName: "req.query", IsSubscript: true},
				{FuncName: "req.params", IsSubscript: true},
				{FuncName: "req.body", IsSubscript: true},
			},
			Sinks: []SinkPattern{
				{FuncName: "fetch", ArgIndex: 0},
				{FuncName: "axios.get", ArgIndex: 0},
				{FuncName: "axios.post", ArgIndex: 0},
				{FuncName: "request", ArgIndex: 0},
				{FuncName: "get", ArgIndex: 0},
			},
		},
		{
			ID:          "TP-JS006",
			Title:       "Code injection (tainted data in eval/Function)",
			Description: "User input flows into eval() or new Function(). Avoid dynamic code execution with untrusted input.",
			Severity:    analysis.SeverityHigh,
			Confidence:  analysis.ConfidenceHigh,
			Language:    "javascript",
			Sources: []SourcePattern{
				{FuncName: "req.query", IsSubscript: true},
				{FuncName: "req.params", IsSubscript: true},
				{FuncName: "req.body", IsSubscript: true},
				{FuncName: "process.argv", IsSubscript: true},
			},
			Sinks: []SinkPattern{
				{FuncName: "eval", ArgIndex: 0},
				{FuncName: "Function", ArgIndex: 0},
				{FuncName: "setTimeout", ArgIndex: 0},
				{FuncName: "setInterval", ArgIndex: 0},
			},
		},
		{
			ID:          "TP-JS007",
			Title:       "Open redirect (tainted data in redirect)",
			Description: "User input flows into a redirect URL. Validate redirect targets against an allowlist.",
			Severity:    analysis.SeverityMedium,
			Confidence:  analysis.ConfidenceMedium,
			Language:    "javascript",
			Sources: []SourcePattern{
				{FuncName: "req.query", IsSubscript: true},
				{FuncName: "req.params", IsSubscript: true},
				{FuncName: "req.body", IsSubscript: true},
			},
			Sinks: []SinkPattern{
				{FuncName: "redirect", ArgIndex: 0},
				{FuncName: "res.redirect", ArgIndex: 0},
			},
		},
	}
}
