package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var ciCmd = &cobra.Command{
	Use:   "ci",
	Short: "CI/CD integration commands",
}

var ciInitCmd = &cobra.Command{
	Use:   "init [platform]",
	Short: "Generate CI/CD integration templates",
	Long: `Generate CI/CD configuration files for integrating PatchFlow into your pipeline.

Supported platforms:
  github    GitHub Actions workflow (.github/workflows/patchflow.yml)
  gitlab    GitLab CI/CD pipeline (.gitlab-ci.yml snippet)
  circleci  CircleCI config (.circleci/config.yml snippet)
  azure     Azure Pipelines (azure-pipelines.yml snippet)
  pre-commit  pre-commit hook (.pre-commit-config.yaml snippet)

Profiles:
  --profile audit     Inform mode, no blocking (first adoption)
  --profile starter   Standard CI profile (stable rules block)
  --profile ci-blocking  All high/critical findings block

Default profile: audit (recommended for first-time adoption).

The generated file includes:
  - PatchFlow scan step
  - SARIF upload (where supported)
  - Config file usage
  - Non-blocking on first run (audit profile)

Examples:
  patchflow ci init github
  patchflow ci init github --profile ci-blocking
  patchflow ci init gitlab --output .gitlab-ci-patchflow.yml`,
	Args: cobra.ExactArgs(1),
	RunE: runCIInit,
}

func init() {
	ciCmd.AddCommand(ciInitCmd)
	rootCmd.AddCommand(ciCmd)
	ciInitCmd.Flags().String("profile", "audit", "CI profile: audit, starter, ci-blocking")
	ciInitCmd.Flags().String("output", "", "Output file path (default: platform-specific)")
}

func runCIInit(cmd *cobra.Command, args []string) error {
	formatter := FormatterFromContext(cmd.Context())
	platform := args[0]
	profile, _ := cmd.Flags().GetString("profile")
	outputPath, _ := cmd.Flags().GetString("output")

	var content string
	var defaultPath string

	switch platform {
	case "github":
		content = githubActionsTemplate(profile)
		defaultPath = ".github/workflows/patchflow.yml"
	case "gitlab":
		content = gitlabCITemplate(profile)
		defaultPath = ".gitlab-ci-patchflow.yml"
	case "circleci":
		content = circleCITemplate(profile)
		defaultPath = ".circleci/patchflow-config.yml"
	case "azure":
		content = azurePipelinesTemplate(profile)
		defaultPath = "azure-patchflow.yml"
	case "pre-commit":
		content = preCommitTemplate(profile)
		defaultPath = ".pre-commit-config.yaml"
	default:
		return formatter.PrintError(fmt.Errorf("unknown platform %q (supported: github, gitlab, circleci, azure, pre-commit)", platform))
	}

	if outputPath == "" {
		outputPath = defaultPath
	}

	// Create directory if needed
	dir := filepath.Dir(outputPath)
	if dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return formatter.PrintError(fmt.Errorf("failed to create directory %s: %w", dir, err))
		}
	}

	// Check if file already exists
	if _, err := os.Stat(outputPath); err == nil {
		return formatter.PrintError(fmt.Errorf("file %s already exists (remove it first or use --output)", outputPath))
	}

	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return formatter.PrintError(fmt.Errorf("failed to write %s: %w", outputPath, err))
	}

	_ = formatter.PrintSuccess(fmt.Sprintf("Generated %s for %s (profile: %s)", outputPath, platform, profile))
	_ = formatter.Print("")
	_ = formatter.Print("Next steps:")
	_ = formatter.Print(fmt.Sprintf("  1. Review %s", outputPath))
	_ = formatter.Print("  2. Install PatchFlow in your CI environment")
	_ = formatter.Print("  3. Run a test scan to verify the setup")
	if profile == "audit" {
		_ = formatter.Print("  4. Once comfortable, switch to --profile starter or ci-blocking")
	}
	return nil
}

func githubActionsTemplate(profile string) string {
	failOn := "never"
	if profile == "ci-blocking" {
		failOn = "high"
	}
	return fmt.Sprintf(`# PatchFlow security scan — generated by 'patchflow ci init github'
# Profile: %s
#
# This workflow runs PatchFlow on every push and PR. It uploads SARIF
# results to GitHub Code Scanning for inline annotation.
#
# Install PatchFlow first:
#   brew install patchflow
#   # or: scoop install patchflow
#   # or: download from https://github.com/Patchflow-security/patchflow-cli/releases

name: PatchFlow Security Scan

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  security-events: write  # required for SARIF upload

jobs:
  patchflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PatchFlow
        run: |
          curl -sSL https://github.com/Patchflow-security/patchflow-cli/releases/latest/download/patchflow_Linux_x86_64.tar.gz | tar xz
          sudo mv patchflow /usr/local/bin/

      - name: Run PatchFlow scan
        run: patchflow scan run --config .patchflow/rules.yaml --format sarif --output patchflow.sarif --fail-on %s
        continue-on-error: true  # set to false once you're ready to block

      - name: Upload SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: patchflow.sarif

      - name: Upload PatchFlow report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: patchflow-report
          path: patchflow.sarif
`, profile, failOn)
}

func gitlabCITemplate(profile string) string {
	failOn := ""
	if profile == "ci-blocking" {
		failOn = "--fail-on high"
	}
	return fmt.Sprintf(`# PatchFlow security scan — generated by 'patchflow ci init gitlab'
# Profile: %s
#
# Add this to your .gitlab-ci.yml or include it as a separate file:
#   include:
#     - local: .gitlab-ci-patchflow.yml
#
# Install PatchFlow in your CI image or use a custom image.

patchflow:scan:
  stage: test
  image: golang:1.26-alpine
  before_script:
    - apk add --no-cache curl tar
    - curl -sSL https://github.com/Patchflow-security/patchflow-cli/releases/latest/download/patchflow_Linux_x86_64.tar.gz | tar xz
    - mv patchflow /usr/local/bin/
  script:
    - patchflow scan run --config .patchflow/rules.yaml --format sarif --output patchflow.sarif %s
  after_script:
    - |
      if [ -f patchflow.sarif ]; then
        echo "PatchFlow SARIF report generated: patchflow.sarif"
      fi
  artifacts:
    when: always
    paths:
      - patchflow.sarif
    reports:
      codequality: patchflow.sarif
  allow_failure: true  # set to false once you're ready to block
`, profile, failOn)
}

func circleCITemplate(profile string) string {
	return fmt.Sprintf(`# PatchFlow security scan — generated by 'patchflow ci init circleci'
# Profile: %s
#
# Add this to your .circleci/config.yml as a job:
#   jobs:
#     patchflow:
#       <<: *patchflow_template

version: 2.1

jobs:
  patchflow:
    docker:
      - image: cimg/go:1.26
    steps:
      - checkout
      - run:
          name: Install PatchFlow
          command: |
            curl -sSL https://github.com/Patchflow-security/patchflow-cli/releases/latest/download/patchflow_Linux_x86_64.tar.gz | tar xz
            sudo mv patchflow /usr/local/bin/
      - run:
          name: Run PatchFlow scan
          command: patchflow scan run --config .patchflow/rules.yaml --format sarif --output patchflow.sarif
          continue-on-error: true  # set to false once ready to block
      - store_artifacts:
          path: patchflow.sarif
          destination: patchflow-report

workflows:
  patchflow:
    jobs:
      - patchflow
`, profile)
}

func azurePipelinesTemplate(profile string) string {
	return fmt.Sprintf(`# PatchFlow security scan — generated by 'patchflow ci init azure'
# Profile: %s
#
# Add this to your azure-pipelines.yml or include as a separate file.

trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Bash@3
    displayName: 'Install PatchFlow'
    inputs:
      targetType: 'inline'
      script: |
        curl -sSL https://github.com/Patchflow-security/patchflow-cli/releases/latest/download/patchflow_Linux_x86_64.tar.gz | tar xz
        sudo mv patchflow /usr/local/bin/

  - task: Bash@3
    displayName: 'Run PatchFlow scan'
    inputs:
      targetType: 'inline'
      script: 'patchflow scan run --config .patchflow/rules.yaml --format sarif --output patchflow.sarif'
    continueOnError: true  # set to false once ready to block

  - task: PublishBuildArtifacts@1
    displayName: 'Publish PatchFlow report'
    inputs:
      PathtoPublish: 'patchflow.sarif'
      ArtifactName: 'patchflow-report'
`, profile)
}

func preCommitTemplate(profile string) string {
	return fmt.Sprintf(`# PatchFlow pre-commit hook — generated by 'patchflow ci init pre-commit'
# Profile: %s
#
# Add this to your .pre-commit-config.yaml:
#   repos:
#     - repo: local
#       hooks:
#         - id: patchflow
#           name: PatchFlow security scan
#           entry: patchflow scan run --config .patchflow/rules.yaml --changed-only
#           language: system
#           pass_filenames: false
#           stages: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: patchflow
        name: PatchFlow security scan
        entry: patchflow scan run --config .patchflow/rules.yaml --changed-only
        language: system
        pass_filenames: false
        stages: [pre-commit]
`, profile)
}
