package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var configValidateCmd = &cobra.Command{
	Use:   "validate [path]",
	Short: "Validate a PatchFlow rules config file",
	Args:  cobra.MaximumNArgs(1),
	RunE:  runConfigValidate,
}

var configMigrateCmd = &cobra.Command{
	Use:   "migrate [path]",
	Short: "Migrate an old config to the current schema",
	Long: `Migrate an old .patchflow/rules.yaml to the current schema.

This command:
  1. Reads the existing config
  2. Adds schema_version: "1.0" if missing
  3. Suggests framework_extensions equivalents for framework_overrides
  4. Writes a new file (.patchflow/rules.migrated.yaml) — does NOT overwrite the original

After reviewing the migrated file, rename it to rules.yaml to adopt.

Example:
  patchflow config migrate
  patchflow config migrate .patchflow/rules.yaml --output .patchflow/rules.v2.yaml`,
	Args: cobra.MaximumNArgs(1),
	RunE: runConfigMigrate,
}

func init() {
	configCmd.AddCommand(configValidateCmd)
	configCmd.AddCommand(configMigrateCmd)
	configMigrateCmd.Flags().String("output", "", "Output path for migrated config (default: .patchflow/rules.migrated.yaml)")
}

func runConfigValidate(cmd *cobra.Command, args []string) error {
	formatter := FormatterFromContext(cmd.Context())

	path := ".patchflow/rules.yaml"
	if len(args) > 0 {
		path = args[0]
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return formatter.PrintError(fmt.Errorf("cannot read %s: %w", path, err))
	}

	var raw map[string]interface{}
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return formatter.PrintError(fmt.Errorf("invalid YAML in %s: %w", path, err))
	}

	warnings := []string{}
	if _, ok := raw["schema_version"]; !ok {
		warnings = append(warnings, "schema_version missing, assuming 1.0")
	}

	if _, ok := raw["framework_overrides"]; ok {
		warnings = append(warnings, "framework_overrides detected — consider migrating to framework_extensions for CWE/category scoping and safe_patterns support")
	}

	if len(warnings) > 0 {
		_ = formatter.PrintSuccess(fmt.Sprintf("Config %s is valid (with warnings)", path))
		for _, w := range warnings {
			_ = formatter.Print("  \u26a0 " + w)
		}
	} else {
		_ = formatter.PrintSuccess(fmt.Sprintf("Config %s is valid", path))
	}
	return nil
}

func runConfigMigrate(cmd *cobra.Command, args []string) error {
	formatter := FormatterFromContext(cmd.Context())

	path := ".patchflow/rules.yaml"
	if len(args) > 0 {
		path = args[0]
	}

	outputPath, _ := cmd.Flags().GetString("output")
	if outputPath == "" {
		outputPath = ".patchflow/rules.migrated.yaml"
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return formatter.PrintError(fmt.Errorf("cannot read %s: %w", path, err))
	}

	// Parse as map for manipulation
	var configMap map[string]interface{}
	if err := yaml.Unmarshal(data, &configMap); err != nil {
		return formatter.PrintError(fmt.Errorf("invalid YAML: %w", err))
	}

	changes := []string{}

	// 1. Add schema_version if missing
	if _, ok := configMap["schema_version"]; !ok {
		configMap["schema_version"] = "1.0"
		changes = append(changes, `added schema_version: "1.0"`)
	}

	// 2. Suggest framework_extensions for framework_overrides
	if overrides, ok := configMap["framework_overrides"].(map[string]interface{}); ok {
		extensions, exists := configMap["framework_extensions"].(map[string]interface{})
		if !exists {
			extensions = map[string]interface{}{}
		}

		for fwName, override := range overrides {
			overrideMap, ok := override.(map[string]interface{})
			if !ok {
				continue
			}
			ext, exists := extensions[fwName].(map[string]interface{})
			if !exists {
				ext = map[string]interface{}{}
			}

			migrated := false
			for _, key := range []string{"custom_sources", "custom_sinks", "custom_sanitizers"} {
				if val, ok := overrideMap[key]; ok {
					if _, has := ext[key]; !has {
						ext[key] = val
						migrated = true
					}
				}
			}

			if migrated {
				extensions[fwName] = ext
				changes = append(changes, fmt.Sprintf("migrated framework_overrides.%s → framework_extensions.%s", fwName, fwName))
			}
		}

		if len(extensions) > 0 {
			configMap["framework_extensions"] = extensions
		}
	}

	// Write migrated file
	out, err := yaml.Marshal(configMap)
	if err != nil {
		return formatter.PrintError(fmt.Errorf("failed to marshal migrated config: %w", err))
	}

	header := fmt.Sprintf("# PatchFlow config — migrated from %s\n# Generated by: patchflow config migrate\n# Review and rename to rules.yaml when ready.\n\n", path)
	finalOutput := header + string(out)

	dir := filepath.Dir(outputPath)
	if dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return formatter.PrintError(fmt.Errorf("failed to create directory %s: %w", dir, err))
		}
	}

	if err := os.WriteFile(outputPath, []byte(finalOutput), 0644); err != nil {
		return formatter.PrintError(fmt.Errorf("failed to write %s: %w", outputPath, err))
	}

	_ = formatter.PrintSuccess(fmt.Sprintf("Migrated config written to %s", outputPath))
	_ = formatter.Print("")
	_ = formatter.Print("Changes made:")
	for _, c := range changes {
		_ = formatter.Print("  + " + c)
	}
	if len(changes) == 0 {
		_ = formatter.Print("  (no changes needed — config already up to date)")
	}
	_ = formatter.Print("")
	_ = formatter.Print("Next steps:")
	_ = formatter.Print(fmt.Sprintf("  1. Review %s", outputPath))
	_ = formatter.Print("  2. Validate: patchflow rules validate " + outputPath)
	_ = formatter.Print(fmt.Sprintf("  3. If satisfied, replace your old config: mv %s %s", outputPath, path))
	return nil
}

// Ensure strings is used
var _ = strings.TrimSpace
