package aspnet

import (
	"regexp"

	"github.com/Patchflow-security/patchflow-cli/internal/analysis"
	"github.com/Patchflow-security/patchflow-cli/internal/sast/frameworks"
)

func Rules() []frameworks.FrameworkRule {
	return []frameworks.FrameworkRule{
		{
			ID:             "PF-ASPNET-SQLI-001",
			Framework:      "aspnet",
			Language:       "csharp",
			CWE:            "CWE-89",
			Title:          "ASP.NET Core SQLi: raw SQL built from request data",
			Severity:       analysis.SeverityHigh,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityBeta,
			FileTypes:      []string{".cs"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`(FromSqlRaw|ExecuteSqlRaw|SqlCommand)\s*\([^)]*(Request\.|HttpContext\.Request|\+)`),
			Sanitizers:     Sanitizers,
			Recommendation: "Use parameterized queries, SqlParameter, or interpolated EF APIs that parameterize values.",
		},
		{
			ID:             "PF-ASPNET-REDIRECT-001",
			Framework:      "aspnet",
			Language:       "csharp",
			CWE:            "CWE-601",
			Title:          "ASP.NET Core open redirect: Redirect with request input",
			Severity:       analysis.SeverityMedium,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityBeta,
			FileTypes:      []string{".cs"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`Redirect\s*\(\s*(Request\.Query|HttpContext\.Request\.Query|.*\[(["'])(returnUrl|next|url)["']\])`),
			Sanitizers:     Sanitizers,
			Recommendation: "Use LocalRedirect or validate with Url.IsLocalUrl before redirecting.",
		},
		{
			ID:             "PF-ASPNET-XSS-001",
			Framework:      "aspnet",
			Language:       "csharp",
			CWE:            "CWE-79",
			Title:          "ASP.NET Core XSS: raw HTML response from request data",
			Severity:       analysis.SeverityHigh,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityBeta,
			FileTypes:      []string{".cs"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`(new\s+HtmlString|Content)\s*\([^)]*(Request\.|HttpContext\.Request)`),
			Sanitizers:     Sanitizers,
			Recommendation: "HTML-encode request-controlled values before writing raw HTML responses.",
		},
		{
			ID:             "PF-ASPNET-SQLI-002",
			Framework:      "aspnet",
			Language:       "csharp",
			CWE:            "CWE-89",
			Title:          "ASP.NET Core SQLi: FromSqlRaw with string interpolation of user input",
			Severity:       analysis.SeverityHigh,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityBeta,
			FileTypes:      []string{".cs"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`FromSqlRaw\s*\(\s*\$?["'].*\{.*(Request|request|query|form|param)`),
			Sanitizers:     Sanitizers,
			Recommendation: "Use FromSqlInterpolated with parameterized values or FromSqlRaw with SqlParameter objects. Never interpolate user input into raw SQL.",
		},
		{
			ID:             "PF-ASPNET-XSS-002",
			Framework:      "aspnet",
			Language:       "csharp",
			CWE:            "CWE-79",
			Title:          "ASP.NET Core XSS: @Html.Raw with user-controlled data",
			Severity:       analysis.SeverityHigh,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityBeta,
			FileTypes:      []string{".cshtml"},
			TemplateTypes:  []string{".cshtml"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`@Html\.Raw\s*\(\s*(Request|Model|ViewData|ViewBag|TempData)`),
			Sanitizers:     Sanitizers,
			Recommendation: "Avoid @Html.Raw with user input. Use @Html.Encode or HtmlEncoder.Default.Encode to escape output.",
		},
		{
			ID:             "PF-ASPNET-DESER-001",
			Framework:      "aspnet",
			Language:       "csharp",
			CWE:            "CWE-502",
			Title:          "ASP.NET Core deserialization: BinaryFormatter.Deserialize with user input",
			Severity:       analysis.SeverityCritical,
			Confidence:     analysis.ConfidenceHigh,
			Maturity:       frameworks.MaturityExperimental,
			FileTypes:      []string{".cs"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`(BinaryFormatter\s*\(\s*\)\.Deserialize|new\s+BinaryFormatter\(\)\.Deserialize|BinaryFormatter\(\)\s*;\s*[^.]*\.Deserialize)`),
			Sanitizers:     Sanitizers,
			Recommendation: "BinaryFormatter is insecure and deprecated. Use JsonSerializer or XmlSerializer with type-safe deserialization instead.",
		},
		{
			ID:             "PF-ASPNET-CMDI-001",
			Framework:      "aspnet",
			Language:       "csharp",
			CWE:            "CWE-78",
			Title:          "ASP.NET Core command injection: Process.Start with request data",
			Severity:       analysis.SeverityCritical,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityExperimental,
			FileTypes:      []string{".cs"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`Process\.Start\s*\(\s*[^,)]*(Request|request|query|form|param)`),
			Sanitizers:     Sanitizers,
			Recommendation: "Avoid passing user input to Process.Start. Use argument lists with proper quoting and validation.",
		},
		{
			ID:             "PF-ASPNET-PATH-001",
			Framework:      "aspnet",
			Language:       "csharp",
			CWE:            "CWE-22",
			Title:          "ASP.NET Core path traversal: Path.Combine with user input",
			Severity:       analysis.SeverityHigh,
			Confidence:     analysis.ConfidenceMedium,
			Maturity:       frameworks.MaturityExperimental,
			FileTypes:      []string{".cs"},
			MatchMode:      frameworks.MatchPattern,
			Pattern:        regexp.MustCompile(`Path\.Combine\s*\(\s*[^,)]*,\s*(Request|request|query|form|param)`),
			Sanitizers:     Sanitizers,
			Recommendation: "Validate and sanitize user input before using in Path.Combine. Check for path traversal sequences (../) and use Path.GetFullPath to canonicalize.",
		},
	}
}
